version: "3"
services:

  mysql:
    image: mysql:5.6
    container_name: snipe-mysql2
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=snipe
      - MYSQL_DATABASE=snipe
  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it2
    restart: always
    depends_on:
      - mysql
    volumes:
      - snipe:/config
    environment:
      - APP_URL=http://192.100.100.246:8090
      - APP_TIMEZONE='Asia/Jakarta'
      - APP_LOCALE=id
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=snipe
      - PGID=1000
      - PUID=1000
      - MAIL_PORT_587_TCP_ADDR=smtp.gmail.com
      - MAIL_PORT_587_TCP_PORT=587
      - MAIL_ENV_FROM_ADDR=it.laplasindo@gmail.com
      - MAIL_ENV_FROM_NAME=IT Support
      - MAIL_ENV_ENCRYPTION=tls
      - MAIL_ENV_USERNAME=it.laplasindo@gmail.com
      - MAIL_ENV_PASSWORD=password_emailnya_bego
    ports:
      - 8090:80

volumes:
    snipe:
    mysql:
